#
# Makefile for the light drivers.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_HUAWEI_FEATURE_PROXIMITY_EVERLIGHT_TMD2771)  += tmd2771.o
obj-$(CONFIG_HUAWEI_FEATURE_PROXIMITY_APDS990X)  += apds990x.o
