#
# Makefile for the accelerometer drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_ACCELEROMETER_ADI_ADXL346)	+= adxl34x.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_ACCELEROMETER_MMA8452)	+= gs_mma8452.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_ACCELEROMETER_ST_LIS3XH)	+= lis3dh_acc.o
