/*The file is auto generated by tools, don't modify it manully.*/

#include "hwgpio_U9501L_VD.c"
#include "hwgpio_U9501L_VC.c"
#include "hwgpio_C8868L_VB.c"
#include "hwgpio_U9501L_VA.c"
#include "hwgpio_U9201L_VC.c"
#include "hwgpio_U9201L_VA.c"
#include "hwgpio_U9501L_VE.c"
#include "hwgpio_U9201L_VB.c"
#include "hwgpio_C8869L_VA.c"
#include "hwgpio_U9501L_VB.c"
#include "hwgpio_C8868L_VA.c"
#include "hwgpio_U9202L_VA.c"
