#
# Makefile for the compass drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_AK8975)   += akm8975.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_AK8963)   += akm8963.o
obj-$(CONFIG_HUAWEI_FEATURE_SENSORS_YAMAHA_COMPASS)   += yas_ori_kernel_driver.o yas_mag_driver-yas530.o yas_mag_kernel_driver.o
