/*********************************************************
CAUTION : This file is Auto Generated by Perl based on *.xls
		so,don't modify this file manually!
*********************************************************/


#include <hsad/config_general_struct.h>
#include <hsad/config_boardids.h>

struct regulator_consumer_supply C8869L_VA_rpm_S1_supply[] = {
	{
		.supply = "8921_s1",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_1 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1225000, \
	      .max_uV =1225000, \
	      .input_uV =1225000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S1_supply), \
     .consumer_supplies = C8869L_VA_rpm_S1_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S1, \
  .default_uV = 1225000, \
  .peak_uA = 100000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_3p20, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 100000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_S2_supply[] = {
	{
		.supply = "8921_s2",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_2 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1300000, \
	      .max_uV =1300000, \
	      .input_uV =1300000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S2_supply), \
     .consumer_supplies = C8869L_VA_rpm_S2_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S2, \
  .default_uV = 1300000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_1p60, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_S3_supply[] = {
	{
		.supply = "8921_s3",
		.dev_name = NULL,
	},
	{
		.supply = "HSUSB_VDDCX",
		.dev_name = "msm_otg",
	},
	{
		.supply = "HSIC_VDDCX",
		.dev_name = "msm_hsic_host",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_3 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =500000, \
	      .max_uV =1150000, \
	      .input_uV =500000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S3_supply), \
     .consumer_supplies = C8869L_VA_rpm_S3_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S3, \
  .default_uV = 1150000, \
  .peak_uA = 100000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_4p80, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 1, \
  .system_uA = 100000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_S4_supply[] = {
	{
		.supply = "8921_s4",
		.dev_name = NULL,
	},
	{
		.supply = "sdc_vccq",
		.dev_name = "msm_sdcc.1",
	},
	{
		.supply = "sdc_vdd",
		.dev_name = "msm_sdcc.2",
	},
	{
		.supply = "sdc_vddp",
		.dev_name = "msm_sdcc.4",
	},
	{
		.supply = "hdmi_vcc",
		.dev_name = "hdmi_msm.0",
	},
	{
		.supply = "VDDIO_CDC",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "CDC_VDD_CP",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "CDC_VDDA_TX",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "CDC_VDDA_RX",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "VDDIO_CDC",
		.dev_name = "tabla2x-slim",
	},
	{
		.supply = "CDC_VDD_CP",
		.dev_name = "tabla2x-slim",
	},
	{
		.supply = "CDC_VDDA_TX",
		.dev_name = "tabla2x-slim",
	},
	{
		.supply = "CDC_VDDA_RX",
		.dev_name = "tabla2x-slim",
	},
	{
		.supply = "vcc_i2c",
		.dev_name = "3-005b",
	},
	{
		.supply = "EXT_HUB_VDDIO",
		.dev_name = "msm_hsic_host",
	},
	{
		.supply = "vcc_i2c",
		.dev_name = "10-0048",
	},
	{
		.supply = "hw_cam_vdig_2",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_cam_vdig_2",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_cam_vdig_2",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_cam_vdig_2",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_cam_vdig_2",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_4 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =1800000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S4_supply), \
     .consumer_supplies = C8869L_VA_rpm_S4_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S4, \
  .default_uV = 1800000, \
  .peak_uA = 100000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_1p60, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 100000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_S7_supply[] = {
	{
		.supply = "8921_s7",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_5 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1150000, \
	      .max_uV =1150000, \
	      .input_uV =1150000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S7_supply), \
     .consumer_supplies = C8869L_VA_rpm_S7_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S7, \
  .default_uV = 1150000, \
  .peak_uA = 100000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_3p20, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 100000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_S8_supply[] = {
	{
		.supply = "8921_s8",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_6 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2050000, \
	      .max_uV =2050000, \
	      .input_uV =2050000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE| REGULATOR_CHANGE_STATUS| REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_S8_supply), \
     .consumer_supplies = C8869L_VA_rpm_S8_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_S8, \
  .default_uV = 2050000, \
  .peak_uA = 100000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_1p60, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 1, \
  .system_uA = 100000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L1_supply[] = {
	{
		.supply = "8921_l1",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_7 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1050000, \
	      .max_uV =1050000, \
	      .input_uV =1050000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L1_supply), \
     .consumer_supplies = C8869L_VA_rpm_L1_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_L1, \
  .default_uV = 1050000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L2_supply[] = {
	{
		.supply = "8921_l2",
		.dev_name = NULL,
	},
	{
		.supply = "dsi_vdda",
		.dev_name = "mipi_dsi.1",
	},
	{
		.supply = "mipi_csi_vdd",
		.dev_name = "msm_csid.0",
	},
	{
		.supply = "mipi_csi_vdd",
		.dev_name = "msm_csid.1",
	},
	{
		.supply = "mipi_csi_vdd",
		.dev_name = "msm_csid.2",
	},
	{
		.supply = "hw_mipi_csi_vdd",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_mipi_csi_vdd",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_mipi_csi_vdd",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_mipi_csi_vdd",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_mipi_csi_vdd",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_8 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1200000, \
	      .max_uV =1200000, \
	      .input_uV =1200000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L2_supply), \
     .consumer_supplies = C8869L_VA_rpm_L2_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_L2, \
  .default_uV = 1200000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L3_supply[] = {
	{
		.supply = "8921_l3",
		.dev_name = NULL,
	},
	{
		.supply = "HSUSB_3p3",
		.dev_name = "msm_otg",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_9 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =3075000, \
	      .max_uV =3075000, \
	      .input_uV =3075000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L3_supply), \
     .consumer_supplies = C8869L_VA_rpm_L3_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L3, \
  .default_uV = 3075000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L4_supply[] = {
	{
		.supply = "8921_l4",
		.dev_name = NULL,
	},
	{
		.supply = "HSUSB_1p8",
		.dev_name = "msm_otg",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_10 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =1800000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L4_supply), \
     .consumer_supplies = C8869L_VA_rpm_L4_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L4, \
  .default_uV = 1800000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 10000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L5_supply[] = {
	{
		.supply = "8921_l5",
		.dev_name = NULL,
	},
	{
		.supply = "sdc_vdd",
		.dev_name = "msm_sdcc.1",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_11 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2950000, \
	      .max_uV =2950000, \
	      .input_uV =2950000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L5_supply), \
     .consumer_supplies = C8869L_VA_rpm_L5_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L5, \
  .default_uV = 2950000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L6_supply[] = {
	{
		.supply = "8921_l6",
		.dev_name = NULL,
	},
	{
		.supply = "sdc_vdd",
		.dev_name = "msm_sdcc.3",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_12 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2950000, \
	      .max_uV =2950000, \
	      .input_uV =2950000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L6_supply), \
     .consumer_supplies = C8869L_VA_rpm_L6_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L6, \
  .default_uV = 2950000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L7_supply[] = {
	{
		.supply = "8921_l7",
		.dev_name = NULL,
	},
	{
		.supply = "sdc_vddp",
		.dev_name = "msm_sdcc.3",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_13 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1850000, \
	      .max_uV =2950000, \
	      .input_uV =1850000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L7_supply), \
     .consumer_supplies = C8869L_VA_rpm_L7_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L7, \
  .default_uV = 2950000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 10000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L8_supply[] = {
	{
		.supply = "8921_l8",
		.dev_name = NULL,
	},
	{
		.supply = "dsi_vdc",
		.dev_name = "mipi_dsi.1",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_14 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2800000, \
	      .max_uV =3000000, \
	      .input_uV =2800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L8_supply), \
     .consumer_supplies = C8869L_VA_rpm_L8_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L8, \
  .default_uV = 3000000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L9_supply[] = {
	{
		.supply = "8921_l9",
		.dev_name = NULL,
	},
	{
		.supply = "vdd",
		.dev_name = "3-0024",
	},
	{
		.supply = "vdd_ana",
		.dev_name = "3-004a",
	},
	{
		.supply = "synaptics_ts_power",
		.dev_name = "3-0070",
	},
	{
		.supply = "atmel_ts_power",
		.dev_name = "3-004a",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_15 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2850000, \
	      .max_uV =2850000, \
	      .input_uV =2850000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L9_supply), \
     .consumer_supplies = C8869L_VA_rpm_L9_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L9, \
  .default_uV = 2850000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L10_supply[] = {
	{
		.supply = "8921_l10",
		.dev_name = NULL,
	},
	{
		.supply = "hw_8921_l10",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_8921_l10",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_8921_l10",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_8921_l10",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_8921_l10",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_16 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2900000, \
	      .max_uV =2900000, \
	      .input_uV =2900000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L10_supply), \
     .consumer_supplies = C8869L_VA_rpm_L10_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L10, \
  .default_uV = 2900000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L11_supply[] = {
	{
		.supply = "8921_l11",
		.dev_name = NULL,
	},
	{
		.supply = "cam_vana",
		.dev_name = "4-001a",
	},
	{
		.supply = "cam_vana",
		.dev_name = "4-006c",
	},
	{
		.supply = "cam_vana",
		.dev_name = "4-0048",
	},
	{
		.supply = "cam_vana",
		.dev_name = "4-0020",
	},
	{
		.supply = "hw_cam_vana",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_cam_vana",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_cam_vana",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_cam_vana",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_cam_vana",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_17 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2850000, \
	      .max_uV =2850000, \
	      .input_uV =2850000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L11_supply), \
     .consumer_supplies = C8869L_VA_rpm_L11_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L11, \
  .default_uV = 2850000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L12_supply[] = {
	{
		.supply = "8921_l12",
		.dev_name = NULL,
	},
	{
		.supply = "cam_vdig",
		.dev_name = "4-001a",
	},
	{
		.supply = "cam_vdig",
		.dev_name = "4-006c",
	},
	{
		.supply = "cam_vdig",
		.dev_name = "4-0048",
	},
	{
		.supply = "cam_vdig",
		.dev_name = "4-0020",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_18 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1200000, \
	      .max_uV =1200000, \
	      .input_uV =1200000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L12_supply), \
     .consumer_supplies = C8869L_VA_rpm_L12_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_L12, \
  .default_uV = 1200000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L14_supply[] = {
	{
		.supply = "8921_l14",
		.dev_name = NULL,
	},
	{
		.supply = "pa_therm",
		.dev_name = "pm8xxx-adc",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_19 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =1800000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L14_supply), \
     .consumer_supplies = C8869L_VA_rpm_L14_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L14, \
  .default_uV = 1800000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L15_supply[] = {
	{
		.supply = "8921_l15",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_20 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =2950000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L15_supply), \
     .consumer_supplies = C8869L_VA_rpm_L15_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L15, \
  .default_uV = 2950000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L16_supply[] = {
	{
		.supply = "8921_l16",
		.dev_name = NULL,
	},
	{
		.supply = "cam_vaf",
		.dev_name = "4-001a",
	},
	{
		.supply = "cam_vaf",
		.dev_name = "4-006c",
	},
	{
		.supply = "cam_vaf",
		.dev_name = "4-0048",
	},
	{
		.supply = "cam_vaf",
		.dev_name = "4-0020",
	},
	{
		.supply = "hw_cam_vaf",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_cam_vaf",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_cam_vaf",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_cam_vaf",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_cam_vaf",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_21 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2800000, \
	      .max_uV =2800000, \
	      .input_uV =2800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L16_supply), \
     .consumer_supplies = C8869L_VA_rpm_L16_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L16, \
  .default_uV = 2800000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L17_supply[] = {
	{
		.supply = "8921_l17",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_22 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =2950000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L17_supply), \
     .consumer_supplies = C8869L_VA_rpm_L17_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L17, \
  .default_uV = 2950000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L18_supply[] = {
	{
		.supply = "8921_l18",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_23 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1300000, \
	      .max_uV =1300000, \
	      .input_uV =1300000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L18_supply), \
     .consumer_supplies = C8869L_VA_rpm_L18_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_L18, \
  .default_uV = 1300000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L21_supply[] = {
	{
		.supply = "8921_l21",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_24 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1900000, \
	      .max_uV =1900000, \
	      .input_uV =1900000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L21_supply), \
     .consumer_supplies = C8869L_VA_rpm_L21_supply, \
     .supply_regulator = "8921_s8", \
  }, \
  .id = RPM_VREG_ID_PM8921_L21, \
  .default_uV = 1900000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L22_supply[] = {
	{
		.supply = "8921_l22",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_25 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2750000, \
	      .max_uV =2750000, \
	      .input_uV =2750000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L22_supply), \
     .consumer_supplies = C8869L_VA_rpm_L22_supply, \
     .supply_regulator = NULL, \
  }, \
  .id = RPM_VREG_ID_PM8921_L22, \
  .default_uV = 2750000, \
  .peak_uA = 0, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L23_supply[] = {
	{
		.supply = "8921_l23",
		.dev_name = NULL,
	},
	{
		.supply = "dsi_vddio",
		.dev_name = "mipi_dsi.1",
	},
	{
		.supply = "hdmi_avdd",
		.dev_name = "hdmi_msm.0",
	},
	{
		.supply = "pll_vdd",
		.dev_name = "pil_riva",
	},
	{
		.supply = "pll_vdd",
		.dev_name = "pil_qdsp6v4.1",
	},
	{
		.supply = "pll_vdd",
		.dev_name = "pil_qdsp6v4.2",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_26 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =1800000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L23_supply), \
     .consumer_supplies = C8869L_VA_rpm_L23_supply, \
     .supply_regulator = "8921_s8", \
  }, \
  .id = RPM_VREG_ID_PM8921_L23, \
  .default_uV = 1800000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 1, \
  .system_uA = 10000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L24_supply[] = {
	{
		.supply = "8921_l24",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_27 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =750000, \
	      .max_uV =1150000, \
	      .input_uV =750000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L24_supply), \
     .consumer_supplies = C8869L_VA_rpm_L24_supply, \
     .supply_regulator = "8921_s1", \
  }, \
  .id = RPM_VREG_ID_PM8921_L24, \
  .default_uV = 1150000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 1, \
  .system_uA = 10000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_L25_supply[] = {
	{
		.supply = "8921_l25",
		.dev_name = NULL,
	},
	{
		.supply = "VDDD_CDC_D",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "CDC_VDDA_A_1P2V",
		.dev_name = "tabla-slim",
	},
	{
		.supply = "VDDD_CDC_D",
		.dev_name = "tabla2x-slim",
	},
	{
		.supply = "CDC_VDDA_A_1P2V",
		.dev_name = "tabla2x-slim",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_28 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1225000, \
	      .max_uV =1225000, \
	      .input_uV =1225000, \
	      .apply_uV = 0, \
	      .always_on =1, \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL| REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE| REGULATOR_CHANGE_DRMS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_L25_supply), \
     .consumer_supplies = C8869L_VA_rpm_L25_supply, \
     .supply_regulator = "8921_s1", \
  }, \
  .id = RPM_VREG_ID_PM8921_L25, \
  .default_uV = 1225000, \
  .peak_uA = 10000, \
  .pull_down_enable = 1, \
  .avg_uA = 0, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 10000, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS1_supply[] = {
	{
		.supply = "8921_lvs1",
		.dev_name = NULL,
	},
	{
		.supply = "hw_cam_vio_2",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_cam_vio_2",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_cam_vio_2",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_cam_vio_2",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_cam_vio_2",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_29 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS1_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS1_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS1, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS2_supply[] = {
	{
		.supply = "8921_lvs2",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_30 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS2_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS2_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS2, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS3_supply[] = {
	{
		.supply = "8921_lvs3",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_31 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS3_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS3_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS3, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS4_supply[] = {
	{
		.supply = "8921_lvs4",
		.dev_name = NULL,
	},
	{
		.supply = "vcc_i2c",
		.dev_name = "3-0024",
	},
	{
		.supply = "vcc_i2c",
		.dev_name = "3-004a",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_32 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS4_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS4_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS4, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS5_supply[] = {
	{
		.supply = "8921_lvs5",
		.dev_name = NULL,
	},
	{
		.supply = "cam_vio",
		.dev_name = "4-001a",
	},
	{
		.supply = "cam_vio",
		.dev_name = "4-006c",
	},
	{
		.supply = "cam_vio",
		.dev_name = "4-0048",
	},
	{
		.supply = "cam_vio",
		.dev_name = "4-0020",
	},
	{
		.supply = "hw_cam_vio",
		.dev_name = "4-006b",
	},
	{
		.supply = "hw_cam_vio",
		.dev_name = "4-006e",
	},
	{
		.supply = "hw_cam_vio",
		.dev_name = "4-0048",
	},
	{
		.supply = "hw_cam_vio",
		.dev_name = "4-005d",
	},
	{
		.supply = "hw_cam_vio",
		.dev_name = "4-006c",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_33 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS5_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS5_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS5, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS6_supply[] = {
	{
		.supply = "8921_lvs6",
		.dev_name = NULL,
	},
	{
		.supply = "vdd_io",
		.dev_name = "spi0.0",
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_34 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS6_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS6_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS6, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_LVS7_supply[] = {
	{
		.supply = "8921_lvs7",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_35 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_LVS7_supply), \
     .consumer_supplies = C8869L_VA_rpm_LVS7_supply, \
     .supply_regulator = "8921_s4", \
  }, \
  .id = RPM_VREG_ID_PM8921_LVS7, \
  .default_uV = 0, \
  .peak_uA = 1000, \
  .pull_down_enable = 1, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM, \
  .freq = RPM_VREG_FREQ_NONE, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}

struct regulator_consumer_supply C8869L_VA_rpm_NCP_supply[] = {
	{
		.supply = "8921_ncp",
		.dev_name = NULL,
	},
};
#define C8869L_VA_RPM_REG_INIT_DATA_36 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1800000, \
	      .max_uV =1800000, \
	      .input_uV =1800000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_rpm_NCP_supply), \
     .consumer_supplies = C8869L_VA_rpm_NCP_supply, \
     .supply_regulator = "8921_l6", \
  }, \
  .id = RPM_VREG_ID_PM8921_NCP, \
  .default_uV = 1800000, \
  .peak_uA = 1000, \
  .pull_down_enable = 0, \
  .avg_uA = 1000, \
  .pin_ctrl = RPM_VREG_PIN_CTRL_NONE, \
  .power_mode = RPM_VREG_POWER_MODE_8960_PWM,\
  .freq = RPM_VREG_FREQ_1p60, \
  .pin_fn = RPM_VREG_PIN_FN_8960_NONE, \
  .force_mode = RPM_VREG_FORCE_MODE_8960_NONE, \
  .state = RPM_VREG_STATE_OFF, \
  .sleep_selectable = 0, \
  .system_uA = 0, \
}



struct rpm_regulator_init_data C8869L_VA_rpm_regulator_init_data[]  = {
C8869L_VA_RPM_REG_INIT_DATA_1,
C8869L_VA_RPM_REG_INIT_DATA_2,
C8869L_VA_RPM_REG_INIT_DATA_3,
C8869L_VA_RPM_REG_INIT_DATA_4,
C8869L_VA_RPM_REG_INIT_DATA_5,
C8869L_VA_RPM_REG_INIT_DATA_6,
C8869L_VA_RPM_REG_INIT_DATA_7,
C8869L_VA_RPM_REG_INIT_DATA_8,
C8869L_VA_RPM_REG_INIT_DATA_9,
C8869L_VA_RPM_REG_INIT_DATA_10,
C8869L_VA_RPM_REG_INIT_DATA_11,
C8869L_VA_RPM_REG_INIT_DATA_12,
C8869L_VA_RPM_REG_INIT_DATA_13,
C8869L_VA_RPM_REG_INIT_DATA_14,
C8869L_VA_RPM_REG_INIT_DATA_15,
C8869L_VA_RPM_REG_INIT_DATA_16,
C8869L_VA_RPM_REG_INIT_DATA_17,
C8869L_VA_RPM_REG_INIT_DATA_18,
C8869L_VA_RPM_REG_INIT_DATA_19,
C8869L_VA_RPM_REG_INIT_DATA_20,
C8869L_VA_RPM_REG_INIT_DATA_21,
C8869L_VA_RPM_REG_INIT_DATA_22,
C8869L_VA_RPM_REG_INIT_DATA_23,
C8869L_VA_RPM_REG_INIT_DATA_24,
C8869L_VA_RPM_REG_INIT_DATA_25,
C8869L_VA_RPM_REG_INIT_DATA_26,
C8869L_VA_RPM_REG_INIT_DATA_27,
C8869L_VA_RPM_REG_INIT_DATA_28,
C8869L_VA_RPM_REG_INIT_DATA_29,
C8869L_VA_RPM_REG_INIT_DATA_30,
C8869L_VA_RPM_REG_INIT_DATA_31,
C8869L_VA_RPM_REG_INIT_DATA_32,
C8869L_VA_RPM_REG_INIT_DATA_33,
C8869L_VA_RPM_REG_INIT_DATA_34,
C8869L_VA_RPM_REG_INIT_DATA_35,
C8869L_VA_RPM_REG_INIT_DATA_36,
};

static struct regulator_consumer_supply C8869L_VA_pmic_L26_supply[] = {
	{
		.supply = "8921_l26",
		.dev_name = NULL,
	},
	{
		.supply = "core_vdd",
		.dev_name = "pil_qdsp6v4.0",
	},
};
#define C8869L_VA_PM8921_REG_PDATA_1 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1050000, \
	      .max_uV =1050000, \
	      .input_uV =1050000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_l26", \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL | REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE | REGULATOR_CHANGE_DRMS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_L26_supply), \
     .consumer_supplies = C8869L_VA_pmic_L26_supply, \
     .supply_regulator = "8921_s7", \
  }, \
  .id = 1, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 200, \
}

static struct regulator_consumer_supply C8869L_VA_pmic_L27_supply[] = {
	{
		.supply = "8921_l27",
		.dev_name = NULL,
	},
	{
		.supply = "core_vdd",
		.dev_name = "pil_qdsp6v4.2",
	},
};
#define C8869L_VA_PM8921_REG_PDATA_2 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1050000, \
	      .max_uV =1050000, \
	      .input_uV =1050000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_l27", \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL | REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE | REGULATOR_CHANGE_DRMS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_L27_supply), \
     .consumer_supplies = C8869L_VA_pmic_L27_supply, \
     .supply_regulator = "8921_s7", \
  }, \
  .id = 2, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 200, \
}

static struct regulator_consumer_supply C8869L_VA_pmic_L28_supply[] = {
	{
		.supply = "8921_l28",
		.dev_name = NULL,
	},
	{
		.supply = "core_vdd",
		.dev_name = "pil_qdsp6v4.1",
	},
};
#define C8869L_VA_PM8921_REG_PDATA_3 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =1050000, \
	      .max_uV =1050000, \
	      .input_uV =1050000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_l28", \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL | REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE | REGULATOR_CHANGE_DRMS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_L28_supply), \
     .consumer_supplies = C8869L_VA_pmic_L28_supply, \
     .supply_regulator = "8921_s7", \
  }, \
  .id = 3, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 200, \
}

static struct regulator_consumer_supply C8869L_VA_pmic_L29_supply[] = {
	{
		.supply = "8921_l29",
		.dev_name = NULL,
	},
};
#define C8869L_VA_PM8921_REG_PDATA_4 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =2050000, \
	      .max_uV =2100000, \
	      .input_uV =2100000, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_l29", \
	      .valid_modes_mask = REGULATOR_MODE_NORMAL | REGULATOR_MODE_IDLE, \
	      .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE | REGULATOR_CHANGE_STATUS | REGULATOR_CHANGE_MODE | REGULATOR_CHANGE_DRMS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_L29_supply), \
     .consumer_supplies = C8869L_VA_pmic_L29_supply, \
     .supply_regulator = "8921_s8", \
  }, \
  .id = 4, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 200, \
}

static struct regulator_consumer_supply C8869L_VA_pmic_USB_OTG_supply[] = {
	{
		.supply = "8921_usb_otg",
		.dev_name = NULL,
	},
};
#define C8869L_VA_PM8921_REG_PDATA_5 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_usb_otg", \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_USB_OTG_supply), \
     .consumer_supplies = C8869L_VA_pmic_USB_OTG_supply, \
     .supply_regulator = "ext_5v", \
  }, \
  .id = 5, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 0, \
}

static struct regulator_consumer_supply C8869L_VA_pmic_HDMI_MVS_supply[] = {
	{
		.supply = "8921_hdmi_mvs",
		.dev_name = NULL,
	},
	{
		.supply = "hdmi_mvs",
		.dev_name = "hdmi_msm.0",
	},
};
#define C8869L_VA_PM8921_REG_PDATA_6 \
{ \
  .init_data = { \
     .constraints = { \
	      .min_uV =0, \
	      .max_uV =0, \
	      .input_uV =0, \
	      .apply_uV = 0, \
	      .always_on =0, \
	      .name = "8921_hdmi_mvs", \
	      .valid_modes_mask = 0, \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     },\
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_pmic_HDMI_MVS_supply), \
     .consumer_supplies = C8869L_VA_pmic_HDMI_MVS_supply, \
     .supply_regulator = "ext_5v", \
  }, \
  .id = 6, \
  .pull_down_enable = 1, \
  .system_uA = 0, \
  .enable_time = 0, \
}



struct pm8xxx_regulator_platform_data C8869L_VA_pm8921_regulator_pdata[]  = {
C8869L_VA_PM8921_REG_PDATA_1,
C8869L_VA_PM8921_REG_PDATA_2,
C8869L_VA_PM8921_REG_PDATA_3,
C8869L_VA_PM8921_REG_PDATA_4,
C8869L_VA_PM8921_REG_PDATA_5,
C8869L_VA_PM8921_REG_PDATA_6,
};

static struct regulator_consumer_supply C8869L_VA_saw_S5_supply[] = {
	{
		.supply = "8921_s5",
		.dev_name = NULL,
	},
	{
		.supply = "krait0",
		.dev_name = NULL,
	},
};
#define C8869L_VA_SAW_REG_PDATA_1 \
{ \
  .constraints = { \
	   .name ="8921_s5", \
	   .min_uV =850000, \
	   .max_uV =1300000, \
	   .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE, \
  }, \
  .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_saw_S5_supply), \
  .consumer_supplies = C8869L_VA_saw_S5_supply, \
}

static struct regulator_consumer_supply C8869L_VA_saw_S6_supply[] = {
	{
		.supply = "8921_s6",
		.dev_name = NULL,
	},
	{
		.supply = "krait1",
		.dev_name = NULL,
	},
};
#define C8869L_VA_SAW_REG_PDATA_2 \
{ \
  .constraints = { \
	   .name ="8921_s6", \
	   .min_uV =850000, \
	   .max_uV =1300000, \
	   .valid_ops_mask = REGULATOR_CHANGE_VOLTAGE, \
  }, \
  .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_saw_S6_supply), \
  .consumer_supplies = C8869L_VA_saw_S6_supply, \
}



struct regulator_init_data C8869L_VA_saw_regulator_pdata[]  = {
C8869L_VA_SAW_REG_PDATA_1,
C8869L_VA_SAW_REG_PDATA_2,
};

struct regulator_consumer_supply C8869L_VA_gpio_EXT_5V_supply[] = {
	{
		.supply = "ext_5v",
		.dev_name = NULL,
	},
};
#define C8869L_VA_GPIO_REG_PDATA_1 \
{ \
  .init_data = { \
     .constraints = { \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_gpio_EXT_5V_supply), \
     .consumer_supplies = C8869L_VA_gpio_EXT_5V_supply, \
     .supply_regulator = NULL, \
  }, \
  .regulator_name = "ext_5v", \
  .gpio = 202, \
  .gpio_label = "ext_5v_en", \
}

struct regulator_consumer_supply C8869L_VA_gpio_EXT_L2_supply[] = {
	{
		.supply = "ext_l2",
		.dev_name = NULL,
	},
	{
		.supply = "vdd_phy",
		.dev_name = "spi0.0",
	},
};
#define C8869L_VA_GPIO_REG_PDATA_2 \
{ \
  .init_data = { \
     .constraints = { \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_gpio_EXT_L2_supply), \
     .consumer_supplies = C8869L_VA_gpio_EXT_L2_supply, \
     .supply_regulator = NULL, \
  }, \
  .regulator_name = "ext_l2", \
  .gpio = 91, \
  .gpio_label = "ext_l2_en", \
}

struct regulator_consumer_supply C8869L_VA_gpio_EXT_3P3V_supply[] = {
	{
		.supply = "ext_3p3v",
		.dev_name = NULL,
	},
	{
		.supply = "vdd_ana",
		.dev_name = "3-005b",
	},
	{
		.supply = "vdd_lvds_3p3v",
		.dev_name = "mipi_dsi.1",
	},
	{
		.supply = "mhl_ext_3p3v",
		.dev_name = "msm_otg",
	},
};
#define C8869L_VA_GPIO_REG_PDATA_3 \
{ \
  .init_data = { \
     .constraints = { \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_gpio_EXT_3P3V_supply), \
     .consumer_supplies = C8869L_VA_gpio_EXT_3P3V_supply, \
     .supply_regulator = NULL, \
  }, \
  .regulator_name = "ext_3p3v", \
  .gpio = 168, \
  .gpio_label = "ext_3p3v_en", \
}

struct regulator_consumer_supply C8869L_VA_gpio_EXT_OTG_SW_supply[] = {
	{
		.supply = "ext_otg_sw",
		.dev_name = NULL,
	},
	{
		.supply = "vbus_otg",
		.dev_name = "msm_otg",
	},
};
#define C8869L_VA_GPIO_REG_PDATA_4 \
{ \
  .init_data = { \
     .constraints = { \
	      .valid_ops_mask = REGULATOR_CHANGE_STATUS, \
     }, \
     .num_consumer_supplies = ARRAY_SIZE(C8869L_VA_gpio_EXT_OTG_SW_supply), \
     .consumer_supplies = C8869L_VA_gpio_EXT_OTG_SW_supply, \
     .supply_regulator = "8921_usb_otg", \
  }, \
  .regulator_name = "ext_otg_sw", \
  .gpio = 193, \
  .gpio_label = "ext_otg_sw_en", \
}



/*The static struct group msm_saw_regulator_pdata will be useful for Board-msm8960.c*/
struct gpio_regulator_platform_data C8869L_VA_gpio_regulator_pdata[]  = {
C8869L_VA_GPIO_REG_PDATA_1,
C8869L_VA_GPIO_REG_PDATA_2,
C8869L_VA_GPIO_REG_PDATA_3,
C8869L_VA_GPIO_REG_PDATA_4,
};

struct hw_config_power_tree C8869L_VA_power_tree={
   .rpm_power_pdata = C8869L_VA_rpm_regulator_init_data,
   .pmic_power_pdata = C8869L_VA_pm8921_regulator_pdata,
   .saw_power_pdata = C8869L_VA_saw_regulator_pdata,
   .gpio_power_pdata = C8869L_VA_gpio_regulator_pdata,
   .rpm_reg_num = 36,
   .pmic_reg_num = 6,
   .saw_reg_num = 2,
   .gpio_reg_num = 4,
};

struct board_id_general_struct config_power_C8869L_VA={
   .name = POWER_MODULE_NAME,
   .board_id = BOARD_ID_C8869L_VA,
   .data_array ={
      .power_tree_ptr = &C8869L_VA_power_tree,
   },
   .list={NULL,NULL},
};
