/*The file is auto generated by scripts, don't modify it manully!*/

#include "hw_U9501L_VD_power_configs.c"
#include "hw_U9501L_VC_power_configs.c"
#include "hw_C8868L_VB_power_configs.c"
#include "hw_U9501L_VA_power_configs.c"
#include "hw_U9201L_VC_power_configs.c"
#include "hw_U9201L_VA_power_configs.c"
#include "hw_U9501L_VE_power_configs.c"
#include "hw_U9201L_VB_power_configs.c"
#include "hw_C8869L_VA_power_configs.c"
#include "hw_U9501L_VB_power_configs.c"
#include "hw_C8868L_VA_power_configs.c"
#include "hw_U9202L_VA_power_configs.c"
