#=============================================================================
#=============================================================================
obj-y += arch_type/
obj-$(CONFIG_INPUT_ACCELEROMETER)	+= accelerometer/
obj-$(CONFIG_INPUT_COMPASS)	+= compass/
obj-$(CONFIG_INPUT_LIGHT_SENSOR)	+= light/
obj-$(CONFIG_INPUT_GYROSCOPE)	+= gyroscope/
obj-$(CONFIG_INPUT_TOUCHSCREEN)	+= touchscreen/
obj-$(CONFIG_HUAWEI_FEATURE_INPUT_TOUCHKEY)       += touchkey/
obj-$(CONFIG_INPUT_FUEL_GAUGE)	+= gauge/
obj-$(CONFIG_HUAWEI_USBSWITCH) += usbswitch/

obj-$(CONFIG_HUAWEI_FEATURE_FELICA_T6ND5) += ak6921af/

obj-y   += sensor_info.o
