##############################################################################
# Makefile for TUNER Driver
##############################################################################

obj-$(CONFIG_ISDBTUNER)	+= tuner_drv.o
obj-$(CONFIG_ISDBTUNER)	+= tuner_drv_wrap.o
obj-$(CONFIG_ISDBTUNER)	+= tuner_drv_hw.o
