#
# Makefile for MHL SiI9244 chip drivers.
obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= si_drv_mhl_tx.o
obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= si_mhl_tx.o
obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= si_mhl_tx_rcp_table.o
obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= sii_reg_access.o
#obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= sii_9244_driver.o
obj-$(CONFIG_HUAWEI_MHL_SII9244)	+= sii_9244_api.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG
