#
# Makefile for the touchkey drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_FEATURE_TOUCHKEY_ATMEL)                += atmel_1060_kpd.o
obj-$(CONFIG_HUAWEI_FEATURE_TOUCHKEY_BL)                   += touchkey_backlight.o


