/* This file is auto-generated by tool, DO NOT modify it manully. */

#ifndef CONFIG_BOARDIDS_H
#define CONFIG_BOARDIDS_H

#define BOARD_ID_U9201L_VB   128
#define BOARD_ID_U9501L_VD   40
#define BOARD_ID_U9202L_VA   3
#define BOARD_ID_C8869L_VA   2
#define BOARD_ID_C8868L_VB   17
#define BOARD_ID_U9501L_VB   8
#define BOARD_ID_C8868L_VA   1
#define BOARD_ID_U9501L_VA   136
#define BOARD_ID_U9501L_VE   56
#define BOARD_ID_U9201L_VA   0
#define BOARD_ID_U9501L_VC   24
#define BOARD_ID_U9201L_VC   16

#endif
