/*The file is auto generated by tools, don't modify it manully.*/
#include <hsad/configdata.h>
#include "hwconfig_enum.h"

config_pair  hw_U9501L_VC_configs [] = {
    {"audio/enhance_type", (const unsigned int)(unsigned int*)"dts", E_CONFIG_DATA_TYPE_STRING }, 
    {"camera/powerseq", (const unsigned int)(unsigned int*)"camera_power_seq_docomo", E_CONFIG_DATA_TYPE_STRING }, 
    {"charger/wireless", (unsigned int)0, E_CONFIG_DATA_TYPE_BOOL }, 
    {"cradle/adapt", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {"gas_gauge/capacity", (unsigned int)1800, E_CONFIG_DATA_TYPE_INT }, 
    {"gas_gauge/firmware_name", (const unsigned int)(unsigned int*)"BQ27510_SANYO_1800", E_CONFIG_DATA_TYPE_STRING }, 
    {"gas_gauge/version", (unsigned int)0x30700d7, E_CONFIG_DATA_TYPE_INT }, 
    {"hdmi/msm", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {"internal_sdcard/exist", (const unsigned int)(unsigned int*)"yes", E_CONFIG_DATA_TYPE_STRING }, 
    {"lcd/id0", (const unsigned int)(unsigned int*)"toshiba_lcd_mipi_video_720p", E_CONFIG_DATA_TYPE_STRING }, 
    {"lcd/id10", (const unsigned int)(unsigned int*)"simulator_mipi_video_vga", E_CONFIG_DATA_TYPE_STRING }, 
    {"lcd/sample/sub_sample1", (const unsigned int)(unsigned int*)"HVGA", E_CONFIG_DATA_TYPE_STRING }, 
    {"lcd/sample/sub_sample2", (unsigned int)0, E_CONFIG_DATA_TYPE_BOOL }, 
    {"lcd/sample/sub_sample3", (unsigned int)80, E_CONFIG_DATA_TYPE_INT }, 
    {"leds/bl_ctl", (const unsigned int)(unsigned int*)"pwm", E_CONFIG_DATA_TYPE_STRING }, 
    {"lightsensor/apds99xx", (const unsigned int)(unsigned int*)"product_docomo", E_CONFIG_DATA_TYPE_STRING }, 
    {"mhl/sii9244", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {"nfc/felica", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {"pm/charge_voltage", (unsigned int)4360, E_CONFIG_DATA_TYPE_INT }, 
    {"pm/current_limt", (const unsigned int)(unsigned int*)"LIMIT_700MA", E_CONFIG_DATA_TYPE_STRING }, 
    {"pm/fuel_gauge", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {"pm/msm_therm", (unsigned int)0, E_CONFIG_DATA_TYPE_BOOL }, 
    {"product/name", (const unsigned int)(unsigned int*)"U9501L_VC", E_CONFIG_DATA_TYPE_STRING }, 
    {"sdcard/TLMM_HDRV_SDC3_CLK/drive_current", (const unsigned int)(unsigned int*)"GPIO_CFG_12MA", E_CONFIG_DATA_TYPE_STRING }, 
    {"sdcard/detect_voltage_level", (const unsigned int)(unsigned int*)"low", E_CONFIG_DATA_TYPE_STRING }, 
    {"sensors/compass", (const unsigned int)(unsigned int*)"bottom", E_CONFIG_DATA_TYPE_STRING }, 
    {"sensors/gsensor", (const unsigned int)(unsigned int*)"bottom", E_CONFIG_DATA_TYPE_STRING }, 
    {"sensors/gyro", (const unsigned int)(unsigned int*)"bottom", E_CONFIG_DATA_TYPE_STRING }, 
    {"tp/resolution", (const unsigned int)(unsigned int*)"720P", E_CONFIG_DATA_TYPE_STRING }, 
    {"usbswitch/fsa9485", (unsigned int)1, E_CONFIG_DATA_TYPE_BOOL }, 
    {0, 0, 0}
 };
struct board_id_general_struct config_common_U9501L_VC= {
	.name=COMMON_MODULE_NAME,
	.board_id=BOARD_ID_U9501L_VC,
	.data_array={.config_pair_ptr=hw_U9501L_VC_configs},
	.list={NULL,NULL},
};
