#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MXT224E_ATMEL)	+= atmel_mXT224E.o

obj-$(CONFIG_TOUCHSCREEN_RMI4_SYNAPTICS)  += synaptics_i2c_rmi_1564.o
